# This is a basic workflow to help you get started with Actions

name: JD CI Sync

on:
  push:
  workflow_dispatch:
  schedule:
    # 每3个小时更新一次代码仓库
    - cron: '1 */3 * * *'

jobs:
  repo-sync:
    env:
      Token: ${{ secrets.Token }}
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: sync 6dylan6-scripts
        uses: repo-sync/github-sync@v2
        if: env.Token
        with:
          source_repo: "https://github.com/6dylan6/jdpro.git"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.Token }}
